name: if_wishes_could_kill
description: If Wishes Could Kill Prank App
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7

flutter:
  uses-material-design: true
